In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#from local helper files
from helper_evaluation import set_all_seeds, set_deterministic
from helper_train import train_model
from helper_plotting import plot_training_loss, plot_accuracy, show_examples
from helper_dataset import get_dataloaders

In [6]:
################# Settings

RANDOM_SEED = 1
BATCH_SIZE = 64
NUM_EPOCHS = 100



In [8]:
set_all_seeds(RANDOM_SEED)
set_deterministic()

In [10]:
train_loader, valid_loader, test_loader = get_dataloaders(batch_size = BATCH_SIZE)

#checking dataset
for images, labels in train_loader:
    print(images.shape)
    print(labels.shape)
    print(labels[:10]) 


torch.Size([64, 1, 28, 28])
torch.Size([64])
tensor([1, 7, 3, 8, 2, 6, 6, 2, 4, 9])
torch.Size([64, 1, 28, 28])
torch.Size([64])
tensor([3, 5, 6, 4, 0, 4, 8, 9, 1, 8])
torch.Size([64, 1, 28, 28])
torch.Size([64])
tensor([1, 1, 4, 8, 9, 5, 7, 0, 7, 6])
torch.Size([64, 1, 28, 28])
torch.Size([64])
tensor([3, 9, 2, 6, 4, 8, 1, 7, 7, 7])


# **Model**

In [14]:
class MLP(torch.nn.Module):
    def __init__(self, num_features, num_hidden, num_classes):
        super().__init__()

        self.num_classes = num_classes

        self.model = torch.nn.Sequential(
            torch.nn.Flatten(),
            torch.nn.Linear(num_features,num_hidden),
            torch.nn.Sigmoid(),
            torch.nn.Linear(num_hidden, num_classes)
        )

    def forward(self,x):
        return self.model(x)


model = MLP(num_features = 28*28,
            num_hidden = 100,
            num_classes = 10)

optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

In [16]:
minibatch_loss_list, train_acc_list, valid_acc_list = train_model(
    model = model,
    num_epochs = NUM_EPOCHS,
    train_loader = train_loader,
    valid_loader = valid_loader,
    test_loader = test_loader,
    optimizer = optimizer,
    device = "cpu"
)

Epoch: 001/100 | Batch 0000/0004 | Loss: 2.3783
Epoch: 001/100 | Train: 13.67% | Validation: 7.81%
Time elapsed: 0.06 min
Epoch: 002/100 | Batch 0000/0004 | Loss: 2.2727
Epoch: 002/100 | Train: 14.06% | Validation: 10.16%
Time elapsed: 0.07 min
Epoch: 003/100 | Batch 0000/0004 | Loss: 2.2464
Epoch: 003/100 | Train: 19.53% | Validation: 11.33%
Time elapsed: 0.08 min
Epoch: 004/100 | Batch 0000/0004 | Loss: 2.2146
Epoch: 004/100 | Train: 13.67% | Validation: 7.81%
Time elapsed: 0.08 min
Epoch: 005/100 | Batch 0000/0004 | Loss: 2.2051
Epoch: 005/100 | Train: 14.84% | Validation: 10.94%
Time elapsed: 0.09 min
Epoch: 006/100 | Batch 0000/0004 | Loss: 2.2037
Epoch: 006/100 | Train: 22.27% | Validation: 14.45%
Time elapsed: 0.10 min
Epoch: 007/100 | Batch 0000/0004 | Loss: 2.2299
Epoch: 007/100 | Train: 35.94% | Validation: 26.56%
Time elapsed: 0.10 min
Epoch: 008/100 | Batch 0000/0004 | Loss: 2.2000
Epoch: 008/100 | Train: 27.73% | Validation: 16.80%
Time elapsed: 0.11 min
Epoch: 009/100 | B