In [63]:
import numpy as np

# 66 have 1
# 2,3 missing
# 4 just 1 person

# mean 1.82
# sd 0.95

v = 0.95 ** 2
print(v)

n = 77
A = np.array([[1/78,2/78,3/78], [0.82**2/n, 0.18**2/n, 1.18**2/n],[1,1,1]])
b = np.array([[1.82-4/78],[v - (2.18**2)/n],[77]])

x = np.linalg.solve(A,b)
x

0.9025


array([[42.02985],
       [ 8.9803 ],
       [25.98985]])

In [56]:
x.round()

array([[42.],
       [ 9.],
       [26.]])

In [58]:
t = np.concatenate( (x.round(), np.array([1]) ), axis = None)


array([42.,  9., 26.,  1.])

In [64]:
x = [1]*42 + [2] * 26 + [3] * 9 + [4]
print(f"mean: {np.mean(x)}, sd: {np.std(x,ddof=1)}")

mean: 1.6025641025641026, sd: 0.7444991969633374


In [ ]:
66